export enum PutIOTransferStatus {
  IN_QUEUE = "IN_QUEUE",
  WAITING = "WAITING",
  DOWNLOADING = "DOWNLOADING",
  COMPLETING = "COMPLETING",
  SEEDING = "SEEDING",
  COMPLETED = "COMPLETED",
  ERROR = "ERROR"
}
